version: '3'
services:
  jaeger-all-in-one:
    image: 'jaegertracing/all-in-one:1.11'
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    command: ["--log-level=debug"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  pyroscope:
    image: 'pyroscope/pyroscope:dev'
    volumes:
      - /Users/dmitry/Dev/ps/pyroscope/tmp/pyroscope-storage:/var/lib/pyroscope
    command:
      - server
    ports:
      - "9090:8080"
  frontend:
    image: 'pyroscope/hotrod-python:dev'
    command:
      - services/frontend/uwsgi.ini
    ports:
      - "8080:80"
    environment:
      - USE_DOCKER_COMPOSE=1
      - PYROSCOPE_APPLICATION_NAME=hotrod.python.frontend
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:8080/
    cap_add:
      - SYS_PTRACE
  customer:
    image: 'pyroscope/hotrod-python:dev'
    command:
      - services/customer/uwsgi.ini
    ports:
      - "8081:80"
    environment:
      - USE_DOCKER_COMPOSE=1
      - PYROSCOPE_APPLICATION_NAME=hotrod.python.customer
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:8080/
    cap_add:
      - SYS_PTRACE
  driver:
    image: 'pyroscope/hotrod-python:dev'
    command:
      - services/driver/uwsgi.ini
    ports:
      - "8082:80"
    environment:
      - USE_DOCKER_COMPOSE=1
      - PYROSCOPE_APPLICATION_NAME=hotrod.python.driver
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:8080/
    cap_add:
      - SYS_PTRACE
  route:
    image: 'pyroscope/hotrod-python:dev'
    command:
      - services/route/uwsgi.ini
    ports:
      - "8083:80"
    environment:
      - USE_DOCKER_COMPOSE=1
      - PYROSCOPE_APPLICATION_NAME=hotrod.python.route
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:8080/
    cap_add:
      - SYS_PTRACE
